
function detectAIVideo() {
  const badges = document.querySelectorAll(".ytBadgeShapeText");
  for (const badge of badges) {
    if (badge.textContent.trim().toUpperCase() === "AI") {
      return {
        element: badge,
        title: "AI Content Detected",
        message: "This video has been labeled as AI-generated by YouTube.",
      };
    }
  }

  const howThisWasMadeElement = document.querySelector("how-this-was-made-section-view-model");
  if (howThisWasMadeElement) {
    const sectionTitleElement = howThisWasMadeElement.querySelector(".ytwHowThisWasMadeSectionViewModelSectionTitle span");
    const sectionTitleText = sectionTitleElement?.textContent ?? "";

    const bodyHeaderElement = howThisWasMadeElement.querySelector(".ytwHowThisWasMadeSectionViewModelBodyHeader span");
    const bodyHeaderText = bodyHeaderElement?.textContent ?? "";

    const bodyTextElement = howThisWasMadeElement.querySelector(".ytwHowThisWasMadeSectionViewModelBodyText span");
    const bodyText = bodyTextElement?.textContent ?? "";

    const lowerHeader = bodyHeaderText.toLowerCase();
    const lowerBody = bodyText.toLowerCase();

    if (
      lowerHeader.includes("altered or synthetic") ||
      lowerHeader.includes("made with ai") ||
      lowerBody.includes("altered or synthetic") ||
      lowerBody.includes("made with ai")
    ) {
      return {
        element: howThisWasMadeElement,
        title: sectionTitleText || "AI Content Detected",
        message: bodyHeaderText || bodyText,
      };
    }
  }

  return null;
}

const detectedElementIds = new Set();

function makeElementUnique(element) {
  if (!element.dataset.uniqueId) {
    element.dataset.uniqueId = crypto.randomUUID();
  }
  return element.dataset.uniqueId;
}

function stopPlayback() {
  document.querySelectorAll("video, audio").forEach((media) => {
    media.pause();
  });
}

let observer = null;

function observeDOM() {
  const targetNode = document.querySelector("ytd-watch-flexy");
  if (!targetNode) {
    return;
  }

  detectedElementIds.clear();

  if (observer) {
    observer.disconnect();
    observer = null;
  }

  function checkElement(recheck) {
    const aiDetection = detectAIVideo();
    if (aiDetection) {
      if (observer) {
        observer.disconnect();
        observer = null;
      }
      const uniqueId = makeElementUnique(aiDetection.element);
      if (!detectedElementIds.has(uniqueId)) {
        detectedElementIds.add(uniqueId);
        setTimeout(stopPlayback, 100);
        createOverlay(aiDetection.title, aiDetection.message);
      } else if (!recheck) {
        setTimeout(() => checkElement(true), 500);
      }
    }
  }

  observer = new MutationObserver(() => checkElement(false));

  observer.observe(targetNode, {
    childList: true,
    subtree: true,
  });

  checkElement(false);
}

window.addEventListener("yt-navigate-finish", observeDOM);

observeDOM();
